# -*- coding: utf-8 -*-
"""Geographical_Locations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uebz60DE0iPTcMn8V-0BjN4UCbj2TXGs
"""

!pip install basemap

from mpl_toolkits.basemap import Basemap
import numpy as np
import matplotlib.pyplot as plt

cities = {
    'name': ['Tehran', 'Esfahan', 'Mashhad', 'Gilan', 'Alborz'],
    'lat': [35.689167, 32.665278, 36.326389, 37.433333, 35.933333],
    'lon': [51.388889, 51.670278, 59.543333, 49.550000, 50.900000],
    'population': [9400000, 2219343, 2307177, 2530696, 2712400]
}

fig=plt.figure()
ax=fig.add_axes([0.1,0.1,0.8,0.8])
m = Basemap(llcrnrlon=45.,llcrnrlat=25.,urcrnrlon=65.,urcrnrlat=40.,\
            rsphere=(6378137.00,6356752.3142),\
            resolution='l',projection='merc',\
            lat_0=35.,lon_0=55.,lat_ts=20.)

m.drawcoastlines()
m.fillcontinents()

for name, lat, lon, pop in zip(cities['name'], cities['lat'], cities['lon'], cities['population']):
    x, y = m(lon, lat)
    m.plot(x, y, 'bo', markersize=5)
    plt.text(x, y, name)

m.drawparallels(np.arange(10,50,5), labels=[1,0,0,0])
m.drawmeridians(np.arange(40,70,5), labels=[0,0,0,1])

ax.set_title('Geographical Locations of Iranian Cities')

plt.show()



plt.bar(cities['name'], cities['population'] )